### ISSUE TITLE
how box convolution works

### ISSUE THREAD

**Issue by jiaozizhao** [shrubb/box-convolutions#11]
Hi,

It is a nice work. 
 In the first figure on your poster, you compared the 3x3 convolution layer and your box convolution layer. I am not clear how the box convolution works. Is it right that for each position (p,q) on the image, you use a box filter which has a relative position x, y to (p,q) and size w,h to calculate the value for (p,q) on the output? You learn the 4 parameters x, y, w, h for each box filter. For example, in the figure, the value for the red anchor pixel position on the output should be the sum of the values in the box. Is it correct? Thanks.

**Comment by shrubb** [comment]
Thanks!
Yes, your explanation is perfectly correct. Output value at a pixel is sum or average of input channel's pixels over a rectangle that is parametrized relative to that position by four learned parameters.

**Comment by jiaozizhao** [comment]
Cool! Thanks very much.

**Comment by jiaozizhao** [comment]
In the paper Forward Pass, you said an input with N maps applied M box filters will result NxM output maps, and the layer has 4xNxM parameters. I don't understand why it 4xNxM parameters, not 4xM parameters for the M box filters? You mean for different map of the input, the same box filter will have different 4 parameters? I am a little confused. Could you explain to me, please? Thanks very much.

**Comment by shrubb** [comment]
An individual bank of M box filters is assigned to each of the N input channels. Thus the first input channel is convolved M times to obtain first M output channels, the second channel is responsible for second M output channels, and so on.
I suggest reading about depthwise convolutions in CNNs. Our layer is exactly a depthwise convolution with special kernels.
