### ISSUE TITLE
Code for paper

### ISSUE THREAD

**Issue by jiaozizhao** [shrubb/box-convolutions#12]
Hi,

May I know when you will release the codes used in your paper? I mean the example code for semantic segmentation. I am looking forward to trying it.

**Comment by shrubb** [comment]
Hi, in progress, stay tuned. The models' definitions should be out in a couple of days.

**Comment by shrubb** [comment]
@jiaozizhao For model definitions, see [BoxENet](https://github.com/shrubb/box-convolutions/blob/master/examples/ENet.py) for example

**Comment by jiaozizhao** [comment]
Thanks very much. I will try it.
