### ISSUE TITLE
Supplemental zip for the paper

### ISSUE THREAD

**Issue by kennyseb** [shrubb/box-convolutions#14]
Hi,
The NIPS archive for the paper gives a 404 for the supplemental material link. [supplemental](https://papers.nips.cc/paper/7859-deep-neural-networks-with-box-convolutions-supplemental.zip)

Can you please provide the zip?

**Comment by shrubb** [comment]
@kennyseb
Hi,
there was no supplemental material apart from the appendix which is in the paper file.
