### ISSUE TITLE
Compared to STN

### ISSUE THREAD

**Issue by kennyseb** [shrubb/box-convolutions#15]
How is box convolutions different than Spatial Transformer networks? Isn't that also a way of generating boxes of interest?

**Comment by shrubb** [comment]
Honestly, I can't see how STNs are "a way of generating boxes of interest". It's just a plane transformation.
To my view, that idea isn't even close. For one, spatial transformer isn't a convolution.

The closest idea that you could probably somehow compare box convolutions to is maybe [ROI warping](https://arxiv.org/abs/1512.04412)...but our approach is still distant.

**Comment by kennyseb** [comment]
Thanks for the clarification, Egor.
