### ISSUE TITLE
Build Problem Windows 10 CUDA10.1 Python Bindings?

### ISSUE THREAD

**Issue by tom23141** [shrubb/box-convolutions#17]
Hi,
I'm trying to compile the box-convolutions using Windows 10 with CUDA 10.1. 
This results in the following error:

```
\python\python36\lib\site-packages\torch\lib\include\pybind11\cast.h(1439): error: expression must be a pointer to a complete object type

  1 error detected in the compilation of "C:/Users/CHRIST~1/AppData/Local/Temp/tmpxft_000010ec_00000000-8_integral_image_cuda.cpp4.ii".
  integral_image_cuda.cu
  error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 2

  ----------------------------------------
Failed building wheel for box-convolution
Running setup.py clean for box-convolution
Failed to build box-convolution
```
Any ideas? Thanks in advance

**Comment by shrubb** [comment]
Might be a PyTorch bug, someone has already reported it at pytorch/pytorch#11004. I wrote a follow-up there, let's see what they'll say about the status of this problem.

**Comment by shrubb** [comment]
Apparently, the problem is in the pybind library. Maybe properly modifying `pybind11\cast.h` can solve it.

**Comment by ZiTian8** [comment]
@shrubb 
Hi,
I'm trying to compile the box-convolutions using Windows 10 with CUDA 10.0.
This results in the following error:

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Users\haha\AppData\Local\Programs\Python\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\haha\\AppData\\Local\\Temp\\pip-req-build-0oqw24hy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\haha\AppData\Local\Temp\pip-record-f3o4zsp_\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\haha\AppData\Local\Temp\pip-req-build-0oqw24hy\

How can I solve this problem?Thanks!

**Comment by shrubb** [comment]
@ZiTian8
Hi, there's really no information in your log, can you run something like `python3 -m pip install . -vvv --log log.txt` and put the detailed log here?

**Comment by ZiTian8** [comment]
i have posted the full log at https://gist.github.com/ZiTian8/810343d4e10971a48330af67f50a52dc
thanks!

**Comment by ZiTian8** [comment]
@shrubb 
i have posted the full log at https://gist.github.com/ZiTian8/810343d4e10971a48330af67f50a52dc
thanks!

**Comment by shrubb** [comment]
@ZiTian8
This is a PyTorch bug, updating PyTorch should fix the problem, other solution is discussed [here](https://discuss.pytorch.org/t/compiler-report-std-ambiguous-symbol-error-under-visual-c-2017/39459).
