### ISSUE TITLE
Doesn't import

### ISSUE THREAD

**Issue by bakirillov** [shrubb/box-convolutions#21]
Hello!

After installing with g++-6, fails to import with the following:

      1 import torch
      2 
----> 3 import box_convolution_cpp_cuda as cpp_cuda
      4 
      5 def reparametrize(

ImportError: /home/bakirillov/anaconda3/envs/lapki/lib/python3.7/site-packages/box_convolution_cpp_cuda.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

Could you please into it?

**Comment by shrubb** [comment]
Anaconda messes paths up. If you use it, be sure to know what you are doing. Particularly here, you have compiled against wrong PyTorch.

Follow the solution at facebookresearch/maskrcnn-benchmark#1
