### ISSUE TITLE
L2 regularization on the box convolution parameters

### ISSUE THREAD

**Issue by lioutasb** [shrubb/box-convolutions#25]
On the [paper](https://papers.nips.cc/paper/7859-deep-neural-networks-with-box-convolutions.pdf) you mention that you use L2 regularization on the box convolution parameters to shrink the box dimensions towards zero. 

Where exactly on the code you do this regularization because I can't find it. You have `weight-decay` flag [here](https://github.com/shrubb/box-convolutions/blob/master/examples/Cityscapes/train.py#L46) but it's not used on the optimizer. Also, if you use this on the optimizer the regularization is going to be applied on the whole network but you specifically mention that you apply regularization on the box convolution parameters only.

**Comment by shrubb** [comment]
Thanks for asking! `weight-decay` is applied [here](https://github.com/shrubb/box-convolutions/blob/ba233c35e73e0d0d9192dd834d267789081083ab/examples/Cityscapes/train.py#L103), though maybe in a slightly complicated manner. It's applied to **all** learnable parameters of the network, including box convolutions' ones; the paper doesn't say that *only* boxes are regularized.

**Comment by lioutasb** [comment]
@shrubb Thank you for your quick response. I did a search with `weight-decay` instead of `weight_decay` that's why I couldn't find it lol. 

I assumed you use regularization only on the box convolution since you didn't mention it on the "Performance" subsection. My bad.

Thank you again for this very interesting work.
