### ISSUE TITLE
[Feature Request] Upgrading to PyTorch 1.4

### ISSUE THREAD

**Issue by aptlin** [shrubb/box-convolutions#26]
Hi @shrubb,

Do you have any plans to update the codebase for PyTorch 1.4 changes? If not, could you please hint at what your ideas are on how to go about this?

Installing with `torch==1.4.0` fails, unfortunately.

Thanks for your awesome work!

**Comment by shrubb** [comment]
Hi, thank you, will do it, hopefully today.

**Comment by shrubb** [comment]
Considering fixed. @sdll, could you please confirm that?
