### ISSUE TITLE
Did you try you impl BoxConv on Unet(Resnet encoder)?

### ISSUE THREAD

**Issue by aidonchuk** [shrubb/box-convolutions#4]
subj
How to set max height, max width? 
Single-process box gen takes too long.

**Comment by shrubb** [comment]
I didn't, but ENet and ERFNet in our paper are very very similar. They are all typical encoder-decoders of residual blocks with max-poolings and upconvolutions. Anyway, I'll soon upload example model definitions I used in the experiments.

Set `max_input_h` and `max_input_w` to maximum height/width of that module's input tensors.

What is box gen? What exactly do you run?

**Comment by aidonchuk** [comment]
320х320 WxH, box gen method is def reset_parameters(self) box_convolution_module.py

**Comment by shrubb** [comment]
Right, it's currently not very fast, I will speed it up. Still, I don't expect that you will run `reset_parameters()` very often. Maybe just once before training.

**Comment by aidonchuk** [comment]
It's work ok on small HxW with one layer. Pls try add it on UNET-like architecture. Thx for repo it's nice!

**Comment by shrubb** [comment]
Here's an example of application: [ENet](https://github.com/shrubb/box-convolutions/blob/master/examples/Cityscapes/models/ENet.py). As far as I know, it's UNet-like, except skip connections.

**Comment by aidonchuk** [comment]
Thx a lot. I'll try it.
